# Generated by Django 5.2.5 on 2025-08-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('level', models.IntegerField(default=1, verbose_name='Nível')),
                ('exp_earn', models.IntegerField(default=10, verbose_name='Experiência Ganha')),
                ('hp', models.IntegerField(default=100, verbose_name='Pontos de Vida')),
                ('attack', models.IntegerField(default=20, verbose_name='Ataque')),
                ('defense', models.IntegerField(default=15, verbose_name='Defesa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Monstro',
                'verbose_name_plural': 'Monstros',
                'ordering': ['level', 'name'],
            },
        ),
    ]
