# Generated by Django 5.2.5 on 2025-08-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='max_hp',
            field=models.IntegerField(default=100, verbose_name='Pontos de Vida Máximos'),
        ),
    ]
