# Generated by Django 5.2.5 on 2025-08-19 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fight', '0001_initial'),
        ('monster', '0002_monster_max_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='max_hp',
        ),
        migrations.CreateModel(
            name='FightMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=100, verbose_name='Pontos de Vida')),
                ('max_hp', models.IntegerField(default=100, verbose_name='Pontos de Vida Máximos')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('exp_earn', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('fight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fight_monsters', to='fight.fight')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monster.monster')),
            ],
        ),
    ]
