# Generated by Django 5.2.5 on 2025-08-22 14:25

import src.django.monster.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0003_remove_monster_max_hp_fightmonster'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=src.django.monster.models.monster_image_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='fightmonster',
            name='hp',
            field=models.IntegerField(default=5, verbose_name='Pontos de Vida'),
        ),
        migrations.AlterField(
            model_name='fightmonster',
            name='max_hp',
            field=models.IntegerField(default=5, verbose_name='Pontos de Vida Máximos'),
        ),
    ]
