# Generated by Django 5.2.5 on 2025-08-16 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Nível')),
                ('exp', models.IntegerField(default=0, verbose_name='Experiência')),
                ('max_hp', models.IntegerField(default=100, verbose_name='HP Máximo')),
                ('hp', models.IntegerField(default=100, verbose_name='HP Atual')),
                ('attack', models.IntegerField(default=20, verbose_name='Ataque')),
                ('defense', models.IntegerField(default=15, verbose_name='Defesa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Herói',
                'verbose_name_plural': 'Heróis',
            },
        ),
    ]
