# Generated by Django 5.2.5 on 2025-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='attack',
            field=models.IntegerField(default=3, verbose_name='Ataque'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='defense',
            field=models.IntegerField(default=1, verbose_name='Defesa'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hp',
            field=models.IntegerField(default=5, verbose_name='HP Atual'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='max_hp',
            field=models.IntegerField(default=5, verbose_name='HP Máximo'),
        ),
    ]
